#!/bin/bash

echo "Do you want to continue? (yes/no)"
read response

if [[ "$response" == "yes" ]]; then
    echo "You chose to continue."
elif [[ "$response" == "no" ]]; then
    echo "You chose not to continue."
else
    echo "Invalid response. Please enter yes or no."
fi
